// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UsersService.Infrastructure;

#nullable disable

namespace UsersService.Infrastructure.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20240729064057_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UsersService.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("Name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("MyUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("512c8fd0-3693-41cf-bdcd-e7b0d1e66123"),
                            FirstName = "Ali",
                            LastName = "Valiev"
                        },
                        new
                        {
                            Id = new Guid("f602d3d8-4412-48dc-88f4-ee18cf51990a"),
                            FirstName = "James",
                            LastName = "Esh"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
